restaurants = ["Anthony's at Spokane Falls",
"Bistango Martini Lounge",
"Casper Fry",
"Central Food",
"Churchill's Steakhouse",
"Ciao Mambo",
"Clinkerdagger",
"Hills' Restaurant and Lounge",
"Hugos On The Hill",
"Italia Trattoria",
"Laguna Cafe",
"Luigi's Italian Restaurant",
"MacKenzie River Pizza, Grill & Pub (North)",
"MacKenzie River Pizza, Grill & Pub (South)",
"Maggie's South Hill Grill",
"MAX at mirabeau",
"Mustard Seed",
"O'Doherty's Irish Grille",
"Post Street Ale House",
"Remington's @Ramada Spokane Airport",
"Ripples Riverside Grill",
"Rock City Grill",
"Saranac Public House",
"Scratch Restaurant & Rain Lounge",
"Spencer's For Steaks And Chops",
"Stacks at Steam Plant",
"Steelhead Bar & Grille",
"Thai Bamboo Restaurants",
"The Palm Court Grill",
"The Q",
"The Safari Room Fresh Grill and Bar",
"Windows of the Seasons"]
